apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Argo CD's externally facing base URL (optional). Required when configuring SSO
  url: http://argocd.kubes-ci.com

  # Enables application status badge feature
  statusbadge.enabled: 'true'

  # Repositories that argocd has access to
  repositories: |
    - url: https://github.com/jordanph/kubes-cd-infrastructure.git

  # A dex connector configuration (optional). See SSO configuration documentation:
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/sso
  # https://github.com/dexidp/dex/tree/master/Documentation/connectors
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Iv1.9a6ffefb256b4133
          clientSecret: $dex.github.clientSecret
        orgs:
          - name: jordanph
