namespace: argocd

resources:
- resources/namespace.yaml
- resources/install.yaml
- resources/ingress.yaml
- applications/argocd-application.yaml
- applications/kubesci-application.yaml

patchesStrategicMerge:
- overlays/argocd-cm.yaml
- overlays/argocd-rbac-cm.yaml
