apiVersion: v1
data:
  repositories: |
    - type: git
      url: https://github.com/jordanph/kubes-cd-infrastructure.git
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2020-05-14T22:26:25Z"
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "833784"
  selfLink: /api/v1/namespaces/argocd/configmaps/argocd-cm
  uid: a9e0081c-9bbe-4809-bd22-bf3a0f5d1be2
data:
  # Argo CD's externally facing base URL (optional). Required when configuring SSO
  url: http://argocd.kubes-ci.com

  # Enables application status badge feature
  statusbadge.enabled: 'true'

  # A dex connector configuration (optional). See SSO configuration documentation:
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/sso
  # https://github.com/dexidp/dex/tree/master/Documentation/connectors
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Iv1.9a6ffefb256b4133
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: jordanph
